Transition to JS
sergeyt/parse-diff pull request #31
Opened 2021-03-11 11:21 UTC by alikhamesy

5 years late to the party, but I transitioned to js as stated in #16. It's pretty much a 1:1 mapping from the old code, except a few ES6/7 features. Also for the build step I put in minified for babel so index would be a little smaller but I'm not sure if that matters.

2021-03-11 20:35 UTC, sergeyt commented
@alikhamesy wow 😄. Thanks for the PR. One small suggestion - lets format JS with Prettier

2021-03-11 21:12 UTC, alikhamesy commented
> lets format JS with Prettier
Sounds good, I'll set that up!

2021-03-11 23:48 UTC, alikhamesy commented
@sergeyt question about `file.index`, should it `['sha...sha', 'fileMode']` or just `'sha...sha'`? right now its the former but I get the feeling it should be the latter?

2021-03-12 18:37 UTC, sergeyt commented
> @sergeyt question about `file.index`, should it `['sha...sha', 'fileMode']` or just `'sha...sha'`? right now its the former but I get the feeling it should be the latter?

I am not sure. I suggest keeping it as it is for now. Maybe need to raise separate discussion for this change

2021-03-12 18:43 UTC, sergeyt requested changes

2021-03-12 19:45 UTC, alikhamesy commented on .eslintrc.json
> +        "tabWidth": 2,
done :)

2021-03-12 20:59 UTC, sergeyt approved these changes

2021-03-12 21:00 UTC, sergeyt commented
@alikhamesy nice, thank you

2021-03-12 21:00 UTC, merged